In Progress - Perfil de Usuario
Molter73/balanpy pull request #15
Opened 2023-01-18 17:19 UTC by bmsjale93

Se ha realizado la pantalla de Perfil de Usuario, con su correspondiente clase java PerfilUsuario que servirá de controlador de la pantalla. 

No se ha cubierto la parte inferior de los botones para tener la referencia de la Portada de la Aplicación.

Hay que añadir el CSS a los botones para que tengan un diseño unificado.

2023-01-25 09:17 UTC, Molter73 requested changes

2023-01-25 09:17 UTC, Molter73 commented on src/main/resources/PerfilUsuario.fxml
> +            <VBox alignment="CENTER_LEFT" maxHeight="-Infinity" prefHeight="300.0" prefWidth="100.0">
Por qué hay in VBox dentro de un GridPane? Te la estás jugando a que las columnas se desajusten. Pon los labels directamente en en GridPane, indicándole columna y fila a cada uno y separa la imagen que no necesariamente tiene que estar alineada con el texto.

2023-01-25 09:17 UTC, Molter73 commented on src/main/resources/PerfilUsuario.fxml
> +                  </Label>
Todos estos labels los vamos a tener que llenar programáticamente, agrégales `fx:id` a cada uno y pon miembros en el controlador para que los podamos acceder directamente. Ej: si al label con el nombre el pones `fx:id="nombre"` en el controlador agregas:
```java
@FXML
private Label nombre;
```

Luego en cualquier evento o en la misma carga de la pantalla podemos hacer:
```
nombre.setText(nuevoNombre);
```

2023-01-25 09:17 UTC, Molter73 commented on src/main/resources/PerfilUsuario.fxml
> +      <GridPane maxWidth="1.7976931348623157E308" prefHeight="400.0">
En lugar de este GridPane, intentaste utilizar un VBox alineado a izquierda para los botones verticales y un HBox para los horizontales? La alineación no quedará perfecta, pero debería quedar bien y agrupa los botones de una forma un poco más lógica.

2023-01-25 09:17 UTC, Molter73 commented on src/main/resources/PerfilUsuario.fxml
> +                  <Button maxHeight="-Infinity" maxWidth="-Infinity" mnemonicParsing="false" onMouseClicked="#HandleDone" prefHeight="80.0" prefWidth="200.0" text="Editar  Perfil" textAlignment="CENT
Ninguno de los botones tiene funcionalidad, pero lo podemos dejar para más adelante.

2023-01-25 13:25 UTC, bmsjale93 commented on src/main/java/org/balanpy/Main.java
> +
Perfecto! En el último commit eliminé esa línea que me indicas

2023-01-25 13:57 UTC, Molter73 commented on src/main/java/org/balanpy/Main.java
> +
Pues el auto-format de eclipse te lo dejó aún peor 😞

2023-01-29 16:41 UTC, Molter73 commented on src/main/resources/PerfilUsuario.fxml
> +            <VBox alignment="CENTER_LEFT" maxHeight="-Infinity" prefHeight="300.0" prefWidth="100.0">
Faltaría quitar la imagen del GridPane, pero por ahora está bien.

2023-01-29 16:41 UTC, Molter73 approved these changes
LGTM!

2023-01-29 16:41 UTC, Molter73 commented
Quita el `In Progress -` del título antes de hacer merge, porfa

2023-01-30 12:59 UTC, merged