se ha creado la rama vacunas y se ha creado el archivo fxml
Molter73/balanpy pull request #22
Opened 2023-01-23 13:01 UTC by Nataliafm1

2023-01-23 15:16 UTC, Molter73 commented
@Nataliafm1 no hace falta que menciones la creación de la rama de git en el commit, sin la rama no podrías subir cambios ni hacer nada, está implicito.

2023-01-25 09:30 UTC, Molter73 requested changes

2023-01-25 09:30 UTC, Molter73 commented on src/main/resources/vacunas.fxml
> +      </Text>
Esto tiene todas las posibilidades de desalinearse, fíjate cómo está hecho en `PortadaAplicacion.fxml` agrupando elementos. Tampoco hace falta que haya botones, se puede agregar eventos para cosas clickeadas que no lo sean.

2023-01-25 09:30 UTC, Molter73 commented on src/main/resources/vacunas.fxml
> +<?xml version="1.0" encoding="UTF-8"?>
El fichero debería llamarse `Vacunas.fxml`, utilizamos CamelCase para esto.

2023-01-29 16:44 UTC, Molter73 approved these changes
LGTM!

2023-01-29 16:51 UTC, Nataliafm1 commented
TIME!! 🥲

2023-01-29 20:26 UTC, merged