Natalia/perfilveterinario
Molter73/balanpy pull request #23
Opened 2023-01-23 15:57 UTC by Nataliafm1

nueva pantalla agregada se crea la rama y el  fxml

2023-01-25 09:39 UTC, Molter73 requested changes
Hay un `Vacunas.java` vacío que no tendría porque estar hasta donde veo, quítalo por favor.

2023-01-25 09:39 UTC, Molter73 commented on src/main/java/org/balanpy/PerfilVeterinario.java
> +	}
Te falta una `}` aquí y por eso no compila

2023-01-25 09:39 UTC, Molter73 commented on src/main/java/org/balanpy/PerfilVeterinario.java
> +public class PerfilVeterinar {
```suggestion
public class PerfilVeterinario {
```

2023-01-25 09:39 UTC, Molter73 commented on src/main/java/org/balanpy/PerfilVeterinario.java
> +import javafx.scene.input.MouseEvent;
```suggestion
```

2023-01-25 09:39 UTC, Molter73 commented on src/main/resources/PerfilVeterinario.fxml
> +<?xml version="1.0" encoding="UTF-8"?>
Si recuerdo bien, esta pantalla iba a quedar con valores fijos de momento, verdad? Si es así, ignora mi próximo comentario.

2023-01-25 09:39 UTC, Molter73 commented on src/main/resources/PerfilVeterinario.fxml
> +      <TextArea layoutX="35.0" layoutY="29.0" prefHeight="92.0" prefWidth="208.0" text="Nombre centro:  La Huellita&#10;Veterinario asignado: Juan Pérez&#10;Teléfono: +34 125 15 70 33&#10;Dirección:
Este componente podría ser una serie de labels en un VBox o GridPane, dependiendo cómo queremos manejarlo para poder acceder a estos campos más fácil.

2023-01-25 09:39 UTC, Molter73 commented on src/main/resources/PerfilVeterinario.fxml
> +            <Image url="@../../../../Desktop/Captura%20de%20Pantalla%202023-01-23%20a%20las%203.48.52%20p.%E2%80%AFm..png" />
Esto no funciona, la imagen tiene que estar en `src/resources/` para que se copie al ejecutable final y tiene que estar puesto así:
```suggestion
            <Image url="@Captura%20de%20Pantalla%202023-01-23%20a%20las%203.48.52%20p.%E2%80%AFm..png" />
```

2023-01-25 09:39 UTC, Molter73 commented on src/main/resources/PerfilVeterinario.fxml
> +            <Image url="@../../../../Downloads/location.png" />
Idem anterior
```suggestion
            <Image url="@location.png" />
```

2023-01-25 09:39 UTC, Molter73 commented on src/main/resources/PerfilVeterinario.fxml
> +            <Image url="@../../../../Downloads/logo-balanpy.png" />
```suggestion
            <Image url="@logo-balanpy.png" />
```

2023-01-29 16:51 UTC, Molter73 reviewed
Un sólo comentario más respecto a la barra inferior que ya tenemos un componente reutilizable. También estaría bien cambiar el título del PR y expandir un poco en la descripción.

2023-01-29 16:51 UTC, Molter73 commented on src/main/resources/PerfilVeterinario.fxml
> +      </ImageView>
Esto está resulto en el fichero `BarraTareas.fxml`, trae los últimos cambios de la rama `main` a esta y mira cómo es puede utilizar en `PortadaAplicacion.fxml`.

2023-01-29 16:52 UTC, Nataliafm1 commented
Voy a buscar ese componente xD me vuelvo loca cuadrando las cosas con el margen

2023-01-30 19:34 UTC, Molter73 commented on src/main/resources/PerfilVeterinario.fxml
> +      </Button>
Agrega esto para tener la barra inferior
```suggestion
      </Button>
      <fx:include source="BarraTareas.fxml" />
```

2023-02-01 18:24 UTC, Molter73 approved these changes
LGTM!

2023-02-01 18:30 UTC, merged