Implementación Mascota e Higiene - In Progress
Molter73/balanpy pull request #24
Opened 2023-01-25 00:59 UTC by bmsjale93

Se han creado los siguientes archivos: 

- Implementación para la Mascota (ImplMascota.java)
- Implementación para la Higiene de la Mascota (ImplHigiene.java)

Además, se ha añadido a la clase Mascota e Higiene las funciones de reload() y Save().

2023-01-25 10:00 UTC, Molter73 requested changes
Después de pasarme todo el código, estoy convencido que los métodos `saveM` y `reloadM` de estas clases no son necesarios, pero si opinas distinto, estoy abierto a escuchar motivos 🙂

2023-01-25 10:00 UTC, Molter73 commented on src/main/java/org/balanpy/Higiene.java
> +	public void reloadM() throws StreamReadException, DatabindException, IOException;
Qué significa la `M` de estos métodos?

2023-01-25 10:00 UTC, Molter73 commented on src/main/java/org/balanpy/MascotaImpl.java
> +	private String grupo_sanguineo = "";
```suggestion
	@JsonProperty(value = "grupo_sanguineo")
	private String grupoSanguineo = "";
```

2023-01-25 10:00 UTC, Molter73 commented on src/main/java/org/balanpy/MascotaImpl.java
> +public class MascotaImpl implements Mascota {
Mascota no debería tener un miembro `higiene`?

2023-01-25 10:00 UTC, Molter73 commented on src/main/java/org/balanpy/MascotaImpl.java
> +	}
Esto sobreescribe el contenido de `mascotas.json` con los datos de una única mascota, en lugar de eso deberíamos tener un array de mascotas y serializar eso, pero esa responsabilidad estará en otra parte de la aplicación.

2023-01-25 10:00 UTC, Molter73 commented on src/main/java/org/balanpy/MascotaImpl.java
> +	}
Esto va a intentar cargar los datos de una mascota desde un fichero que tiene un array de mascotas, no va a funcionar y debería manejarlo otra parte de la aplicación.

2023-01-25 10:00 UTC, Molter73 commented on src/main/java/org/balanpy/MascotaImpl.java
> +				|| grCaseInsensitive.equals(DEA7) || grCaseInsensitive.equals(DEA8);
Esto no va a funcionar, los `DEA` están definidos como `DEA-` pero estás pasando el grupo sanguineo a minúsculas.

2023-01-25 10:00 UTC, Molter73 commented on src/main/java/org/balanpy/MascotaImpl.java
> +	public static boolean isValidGrupoSanguineo(String grupo_sanguineo) {
```suggestion
	public static boolean isValidGrupoSanguineo(String grupoSanguineo) {
```

2023-01-25 10:00 UTC, Molter73 commented on src/main/java/org/balanpy/MascotaImpl.java
> +	}
Agrega tests para estas dos funciones, de esa forma puedes validar que realmente hacen lo que piensas.

2023-01-25 15:47 UTC, bmsjale93 commented on src/main/java/org/balanpy/MascotaImpl.java
> +	}
Esto me he perdido un poco y no se bien como hacerlo, he estado buscando información pero me sigue sin quedar claro del todo.

2023-01-25 15:49 UTC, Molter73 commented on src/main/java/org/balanpy/MascotaImpl.java
> +	}
Aquí hay unos tests para la clase usuario, te deberían servir de base para estos: https://github.com/Molter73/balanpy/blob/main/src/test/java/tests/UsuarioImplTest.java

2023-01-29 16:56 UTC, Molter73 approved these changes
Bien por el agregado de tests! Por favor quita el `- In Progress` del título antes de hacer el merge.

2023-01-29 16:56 UTC, Molter73 commented on src/main/java/org/balanpy/MascotaImpl.java
> +public class MascotaImpl implements Mascota, Higiene {
No estoy convencido que querramos que `MascotaImpl` implemente `Mascota` e `Higiene`, deberíamos tener un `HigieneImpl` y `MascotaImpl` debería tener un campo privado de tipo `Higiene`. Podemos dejarlo así por ahora para ir avanzando con otras cosas, pero 95% que lo vamos a tener que cambiar en un PR subsiguiente.

2023-01-31 10:40 UTC, Molter73 approved these changes
Hace falta agregar un par de setter/getter para el campo higiene, por lo demás ya está bien.

2023-01-31 10:40 UTC, Molter73 commented on src/main/java/org/balanpy/MascotaImpl.java
> +	HigieneImpl higiene = new HigieneImpl();
```suggestion
	private HigieneImpl higiene = new HigieneImpl();
```

2023-02-06 19:43 UTC, merged